apiVersion: v1
kind: Template
metadata:
  name: package-extract-buildconfig-bissenbay
  annotations:
    description: This is Thoth Core - Package Extract BuildConfig Bissenbay
    openshift.io/display-name: "Thoth: Package Extract BuildConfig Bissenbay"
    version: 0.4.0
    tags: poc,thoth,ai-stacks,package-extract, bissenbay
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: |-
      This template defines resources needed to deploy Thoth
      Package Extract as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.4.0
  labels:
    template: package-extract-buildconfig-bissenbay
    app: thoth
    component: package-extract-bissenbay

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: package-extract-bissenbay
      annotations:
        thoth-station.ninja/template-version: 0.4.0
      labels:
        app: thoth
        component: package-extract-bissenbay
    spec:
      containers:
      resources:
        requests:
          cpu: 2
          memory: 512Mi
        limits:
          cpu: 2
          memory: 1024Mi
      output:
        to:
          kind: ImageStreamTag
          name: "package-extract-bissenbay:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: "${GITHUB_URL}"
          ref: "${GITHUB_REF}"
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile
          secrets:
            - secretSource:
                name: "entitlement"
              mountPath: "/etc/pki/entitlement"
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret

parameters:
  - description: Name of the github repository
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/bissenbay/package-extract'

  - description: Git reference to be used
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'port-to-ubi8'

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
